#include "bsp_gpio.h"

void OUTPUT_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct={0};

  CHANNEL1_RCC_CLK_ENABLE();
  CHANNEL2_RCC_CLK_ENABLE();
  CHANNEL3_RCC_CLK_ENABLE();
  CHANNEL4_RCC_CLK_ENABLE();
	START_RCC_CLK_ENABLE();
  CLOCK_RCC_CLK_ENABLE();
  
	HAL_GPIO_WritePin(CHANNEL1_GPIO,CHANNEL1_GPIO_PIN,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(CHANNEL2_GPIO,CHANNEL2_GPIO_PIN,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(CHANNEL3_GPIO,CHANNEL3_GPIO_PIN,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(CHANNEL4_GPIO,CHANNEL4_GPIO_PIN,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(START_GPIO,START_GPIO_PIN,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(CLOCK_GPIO,CLOCK_GPIO_PIN,GPIO_PIN_RESET);

  GPIO_InitStruct.Pin = CHANNEL1_GPIO_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(CHANNEL1_GPIO, &GPIO_InitStruct); 

  GPIO_InitStruct.Pin = CHANNEL2_GPIO_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(CHANNEL2_GPIO, &GPIO_InitStruct); 

  GPIO_InitStruct.Pin = CHANNEL3_GPIO_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(CHANNEL3_GPIO, &GPIO_InitStruct); 
  
  GPIO_InitStruct.Pin = CHANNEL4_GPIO_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(CHANNEL4_GPIO, &GPIO_InitStruct); 

  GPIO_InitStruct.Pin = START_GPIO_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(START_GPIO, &GPIO_InitStruct); 
  
  GPIO_InitStruct.Pin = CLOCK_GPIO_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(CLOCK_GPIO, &GPIO_InitStruct); 
}